services:
  mage:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "6789:6789"
    volumes:
      - ./classical-composer-prediction:/home/src/classical-composer-prediction
      - ./data:/home/src/data
    env_file:
      - .env
    depends_on:
      - mlflow
    networks:
      - mage-mlflow-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow-artifacts:/mlflow-artifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri ${MLFLOW_BACKEND_URI}
      --default-artifact-root file:///mlflow-artifacts
    networks:
      - mage-mlflow-network

networks:
  mage-mlflow-network:
    driver: bridge